name: Gradle Package

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: docker-compose
        run: sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - name: docker-compose-p
        run: sudo chmod +x /usr/local/bin/docker-compose
      - name: docker-compose-up
        run: docker-compose up --build -d
      - name: sleep
        run: sleep 15
      - name: docker ps
        run: docker ps
      - name: java
        run: java -jar artifacts/aqa-shop.jar &
      - name: Permission
        run: chmod +x ./gradlew
      - name: Test with Gradle
        run: ./gradlew test --info -Dselenide.headless=true

